name: 🚀 Bump pre-release version

on:
  workflow_dispatch:
    inputs:
      preid:
        description: "Prerelease ID"
        required: true
        default: "alpha"
        type: choice
        options:
          - alpha
          - beta
          - rc

jobs:
  bump-chore:
    name: Chore
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash

    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: 'lts/*'
          registry-url: "https://registry.npmjs.org"

      - uses: pnpm/action-setup@v2
        id: pnpm-install
        with:
          version: 7
          run_install: false

      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.GH_ACCESS_TOKEN }}
          fetch-depth: 2

      - name: ⚙️ Update version
        run: |
          cd lib
          pnpm version --preid ${{ github.event.inputs.preid }} --git-tag-version=false prerelease || true
        # ` || true` - pnpm will return error because of monorepository dev dependencies

      - id: Commit
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          PACKAGE_VERSION=$(node -p "require('./lib/package.json').version")
          git commit -am "chore: v${PACKAGE_VERSION}"

      - run: git push
