name: 📋 Verify pull requests

on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash

    steps:

      - uses: actions/checkout@v3
        id: setup-git-checkout
        with:
          fetch-depth: 25

      - uses: actions/setup-node@v4
        id: setup-node
        with:
          node-version: 'lts/*'
          cache: 'yarn'

      - name: 📌 Install dependencies
        run: yarn install --frozen-lockfile

      - name: 🔨 Build
        run: yarn build

      - uses: actions/cache@v3
        name: 🗃️ Cache build
        timeout-minutes: 10
        id: cache-build
        with:
          path: ./*
          key: ${{ github.sha }}-${{ github.run_number }}

  test:
    runs-on: ubuntu-latest
    needs: build
    defaults:
      run:
        shell: bash
    strategy:
      matrix:
        node-version: [18.x, 20.x, 21.x, 22.x]

    steps:
      - uses: actions/cache@v3
        name: 🗃️ Restore build cache
        timeout-minutes: 5
        id: restore-build
        with:
          path: ./*
          key: ${{ github.sha }}-${{ github.run_number }}

      - uses: actions/setup-node@v4
        id: setup-node
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'yarn'

      - name: 🧪 Tests
        run: yarn test

  lint:
    runs-on: ubuntu-latest
    needs: build
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/cache@v3
        name: 🗃️ Restore build cache
        timeout-minutes: 5
        id: restore-build
        with:
          path: ./*
          key: ${{ github.sha }}-${{ github.run_number }}

      - uses: actions/setup-node@v4
        id: setup-node
        with:
          cache: 'yarn'

      - name: ✨ Lint
        run: yarn lint
